In [26]:
import pandas as pd
import geopandas as gpd
from shapely.geometry import Point
from sklearn.cluster import KMeans
import numpy as np

In [17]:
gdf = gpd.read_file("BR_setores_CD2022.shp")

In [18]:
ponto = Point(-46.6333, -23.5505)
resultado = gdf[gdf.contains(ponto)]
resultado['SITUACAO']

354443    Urbana
Name: SITUACAO, dtype: str

In [19]:
gdf['lon'] = gdf['geometry'].apply(lambda g: g.centroid.x)
gdf['lat'] = gdf['geometry'].apply(lambda g: g.centroid.y)
gdf

,CD_SETOR,SITUACAO,CD_SIT,CD_TIPO,AREA_KM2,CD_REGIAO,NM_REGIAO,CD_UF,NM_UF,CD_MUN,...,NM_AGLOM,CD_RGINT,NM_RGINT,CD_RGI,NM_RGI,CD_CONCURB,NM_CONCURB,geometry,lon,lat
0,120040105000708,Urbana,1,0,0.038450,1,Norte,12,Acre,1200401,...,NaN,1201,Rio Branco,120001,Rio Branco,1200401,Rio Branco,"POLYGON ((-67.83814 -9.93462, -67.83862 -9.935...",-67.838958,-9.934559
1,130340305000118,Urbana,1,0,0.014565,1,Norte,13,Amazonas,1303403,...,NaN,1304,Parintins,130010,Parintins,1303403,Parintins,"POLYGON ((-56.72629 -2.62753, -56.72667 -2.627...",-56.727220,-2.627210
2,150140275000317,Urbana,1,0,0.022382,1,Norte,15,Pará,1501402,...,NaN,1501,Belém,150001,Belém,1501402,Belém/PA,"POLYGON ((-48.49293 -1.41145, -48.4932 -1.4134...",-48.493569,-1.412550
3,150442205000199,Urbana,1,0,0.011190,1,Norte,15,Pará,1504422,...,NaN,1501,Belém,150001,Belém,1501402,Belém/PA,"POLYGON ((-48.333 -1.38807, -48.33307 -1.38786...",-48.332172,-1.387773
4,150560110000009,Urbana,3,0,0.186789,1,Norte,15,Pará,1505601,...,NaN,1502,Castanhal,150006,Capanema,NaN,NaN,"POLYGON ((-47.19578 -1.18598, -47.1958 -1.1856...",-47.194287,-1.185464
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
468094,530010805440139,Rural,8,0,1.780541,5,Centro-Oeste,53,Distrito Federal,5300108,...,NaN,5301,Distrito Federal,530001,Distrito Federal,5300108,Brasília/DF,"POLYGON ((-47.89044 -15.60213, -47.89047 -15.6...",-47.897231,-15.595971
468095,530010805440140,Urbana,1,0,0.080864,5,Centro-Oeste,53,Distrito Federal,5300108,...,NaN,5301,Distrito Federal,530001,Distrito Federal,5300108,Brasília/DF,"POLYGON ((-47.83752 -15.6349, -47.83943 -15.63...",-47.838467,-15.633122
468096,530010805440141,Urbana,1,0,0.067327,5,Centro-Oeste,53,Distrito Federal,5300108,...,NaN,5301,Distrito Federal,530001,Distrito Federal,5300108,Brasília/DF,"POLYGON ((-47.83943 -15.63491, -47.83752 -15.6...",-47.838503,-15.636393
468097,530010805440142,Urbana,3,0,0.229041,5,Centro-Oeste,53,Distrito Federal,5300108,...,NaN,5301,Distrito Federal,530001,Distrito Federal,5300108,Brasília/DF,"POLYGON ((-47.8889 -15.63801, -47.88887 -15.63...",-47.882062,-15.640696
468098,530010805440143,Urbana,3,0,0.059100,5,Centro-Oeste,53,Distrito Federal,5300108,...,NaN,5301,Distrito Federal,530001,Distrito Federal,5300108,Brasília/DF,"POLYGON ((-47.88239 -15.64082, -47.88258 -15.6...",-47.885401,-15.639975

In [20]:
gdf.drop('geometry', axis=1, inplace=True)

In [42]:
df = pd.DataFrame(gdf)
df

,CD_SETOR,SITUACAO,CD_SIT,CD_TIPO,AREA_KM2,CD_REGIAO,NM_REGIAO,CD_UF,NM_UF,CD_MUN,...,CD_AGLOM,NM_AGLOM,CD_RGINT,NM_RGINT,CD_RGI,NM_RGI,CD_CONCURB,NM_CONCURB,lon,lat
0,120040105000708,Urbana,1,0,0.038450,1,Norte,12,Acre,1200401,...,NaN,NaN,1201,Rio Branco,120001,Rio Branco,1200401,Rio Branco,-67.838958,-9.934559
1,130340305000118,Urbana,1,0,0.014565,1,Norte,13,Amazonas,1303403,...,NaN,NaN,1304,Parintins,130010,Parintins,1303403,Parintins,-56.727220,-2.627210
2,150140275000317,Urbana,1,0,0.022382,1,Norte,15,Pará,1501402,...,NaN,NaN,1501,Belém,150001,Belém,1501402,Belém/PA,-48.493569,-1.412550
3,150442205000199,Urbana,1,0,0.011190,1,Norte,15,Pará,1504422,...,NaN,NaN,1501,Belém,150001,Belém,1501402,Belém/PA,-48.332172,-1.387773
4,150560110000009,Urbana,3,0,0.186789,1,Norte,15,Pará,1505601,...,NaN,NaN,1502,Castanhal,150006,Capanema,NaN,NaN,-47.194287,-1.185464
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
468094,530010805440139,Rural,8,0,1.780541,5,Centro-Oeste,53,Distrito Federal,5300108,...,NaN,NaN,5301,Distrito Federal,530001,Distrito Federal,5300108,Brasília/DF,-47.897231,-15.595971
468095,530010805440140,Urbana,1,0,0.080864,5,Centro-Oeste,53,Distrito Federal,5300108,...,NaN,NaN,5301,Distrito Federal,530001,Distrito Federal,5300108,Brasília/DF,-47.838467,-15.633122
468096,530010805440141,Urbana,1,0,0.067327,5,Centro-Oeste,53,Distrito Federal,5300108,...,NaN,NaN,5301,Distrito Federal,530001,Distrito Federal,5300108,Brasília/DF,-47.838503,-15.636393
468097,530010805440142,Urbana,3,0,0.229041,5,Centro-Oeste,53,Distrito Federal,5300108,...,NaN,NaN,5301,Distrito Federal,530001,Distrito Federal,5300108,Brasília/DF,-47.882062,-15.640696
468098,530010805440143,Urbana,3,0,0.059100,5,Centro-Oeste,53,Distrito Federal,5300108,...,NaN,NaN,5301,Distrito Federal,530001,Distrito Federal,5300108,Brasília/DF,-47.885401,-15.639975

In [43]:
df['score'] = 1
df.loc[df['SITUACAO']=='Urbana', 'score'] = 2
df['city'] = df['NM_MUN']
df['uf'] = df['NM_UF']
df['ramo'] = 'ALL'

export = df[['city','lat','lon','score','ramo','uf']]
export

              city        lat        lon  score ramo                uf
0       Rio Branco  -9.934559 -67.838958      2  ALL              Acre
1        Parintins  -2.627210 -56.727220      2  ALL          Amazonas
2            Belém  -1.412550 -48.493569      2  ALL              Pará
3         Marituba  -1.387773 -48.332172      2  ALL              Pará
4        Peixe-Boi  -1.185464 -47.194287      2  ALL              Pará
...            ...        ...        ...    ...  ...               ...
468094    Brasília -15.595971 -47.897231      1  ALL  Distrito Federal
468095    Brasília -15.633122 -47.838467      2  ALL  Distrito Federal
468096    Brasília -15.636393 -47.838503      2  ALL  Distrito Federal
468097    Brasília -15.640696 -47.882062      2  ALL  Distrito Federal
468098    Brasília -15.639975 -47.885401      2  ALL  Distrito Federal

[468099 rows x 6 columns]

In [44]:
coords = np.radians(export[['lat', 'lon']])

kmeans = KMeans(n_clusters=7000, random_state=42)
export['cluster'] = kmeans.fit_predict(coords)

export

,city,lat,lon,score,ramo,uf,cluster
0,Rio Branco,-9.934559,-67.838958,2,ALL,Acre,4834
1,Parintins,-2.627210,-56.727220,2,ALL,Amazonas,654
2,Belém,-1.412550,-48.493569,2,ALL,Pará,6052
3,Marituba,-1.387773,-48.332172,2,ALL,Pará,5610
4,Peixe-Boi,-1.185464,-47.194287,2,ALL,Pará,2767
...,...,...,...,...,...,...,...
468094,Brasília,-15.595971,-47.897231,1,ALL,Distrito Federal,1892
468095,Brasília,-15.633122,-47.838467,2,ALL,Distrito Federal,1892
468096,Brasília,-15.636393,-47.838503,2,ALL,Distrito Federal,1892
468097,Brasília,-15.640696,-47.882062,2,ALL,Distrito Federal,1892
468098,Brasília,-15.639975,-47.885401,2,ALL,Distrito Federal,1892

In [45]:
score = export[['cluster','score']].groupby('cluster').mean().reset_index().rename(columns={'score':'score_medio'})
score['score'] = pd.qcut(
    score['score_medio'],
    q=4,
    labels=[1, 2, 3, 4]
)
score.drop(columns='score_medio', inplace=True)
score

      cluster score
0           0     3
1           1     2
2           2     2
3           3     1
4           4     4
...       ...   ...
6995     6995     3
6996     6996     3
6997     6997     1
6998     6998     1
6999     6999     2

[7000 rows x 2 columns]

In [46]:
export = pd.merge(export, score, on='cluster', how='inner').drop_duplicates(subset='cluster', keep='first')
export['score_x'] = export['score_y']
export.drop(columns=['cluster', 'score_y'], inplace=True)
export.rename(columns={'score_x': 'score'}, inplace=True)
export

              city        lat        lon score ramo                uf
0       Rio Branco  -9.934559 -67.838958     4  ALL              Acre
1        Parintins  -2.627210 -56.727220     4  ALL          Amazonas
2            Belém  -1.412550 -48.493569     4  ALL              Pará
3         Marituba  -1.387773 -48.332172     4  ALL              Pará
4        Peixe-Boi  -1.185464 -47.194287     4  ALL              Pará
...            ...        ...        ...   ...  ...               ...
464135    Brasília -15.610436 -47.630196     4  ALL  Distrito Federal
464280    Brasília -15.811988 -47.508715     1  ALL  Distrito Federal
464546    Brasília -15.846173 -47.675984     4  ALL  Distrito Federal
464625    Brasília -15.885123 -48.022452     4  ALL  Distrito Federal
465308    Brasília -15.819015 -47.973151     4  ALL  Distrito Federal

[7000 rows x 6 columns]

In [47]:
export.to_csv('mapinha.csv',index=False)

In [24]:
export['score']

0         2
1         2
2         2
3         2
4         2
         ..
468094    1
468095    2
468096    2
468097    2
468098    2
Name: score, Length: 468099, dtype: int64

In [24]:
https://www.ibge.gov.br/geociencias/organizacao-do-territorio/malhas-territoriais.html
https://github.com/kelvins/municipios-brasileiros?utm_source=chatgpt.com