In [2]:
import h3
import pandas as pd
import geopandas as gpd
import geodatasets

C:\Users\lmene\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [10]:
path = geodatasets.get_path("naturalearth.land")

world = gpd.read_file(path)
world = gpd.read_file(
    "https://naturalearth.s3.amazonaws.com/110m_cultural/ne_110m_admin_0_countries.zip"
)

brazil = world[world["ADMIN"] == "Brazil"].geometry.iloc[0]

coords = list(brazil.exterior.coords)
polygon = h3.LatLngPoly(
    [(lat, lng) for lng, lat in coords]
)

res5_cells = list(
    h3.h3shape_to_cells(
        polygon,
        res=5
    )
)

In [11]:
data = {
    "res5": res5_cells
}

for res in range(4, -1, -1):
    data[f"res{res}"] = [
        h3.cell_to_parent(h, res)
        for h in res5_cells
    ]

df = pd.DataFrame(data)
df

,res5,res4,res3,res2,res1,res0
0,858a44dbfffffff,848a44dffffffff,838a44fffffffff,828a47fffffffff,818a7ffffffffff,808bfffffffffff
1,85a8250bfffffff,84a8251ffffffff,83a825fffffffff,82a827fffffffff,81a83ffffffffff,80a9fffffffffff
2,858111b3fffffff,848111bffffffff,838111fffffffff,828117fffffffff,81813ffffffffff,8081fffffffffff
3,85a82193fffffff,84a8219ffffffff,83a821fffffffff,82a827fffffffff,81a83ffffffffff,80a9fffffffffff
4,858f6bc7fffffff,848f6bdffffffff,838f6bfffffffff,828f6ffffffffff,818f7ffffffffff,808ffffffffffff
...,...,...,...,...,...,...
31456,858a0693fffffff,848a069ffffffff,838a06fffffffff,828a07fffffffff,818a3ffffffffff,808bfffffffffff
31457,85a90bdbfffffff,84a90bdffffffff,83a90bfffffffff,82a90ffffffffff,81a93ffffffffff,80a9fffffffffff
31458,858a031bfffffff,848a031ffffffff,838a03fffffffff,828a07fffffffff,818a3ffffffffff,808bfffffffffff
31459,858a95a7fffffff,848a95bffffffff,838a95fffffffff,828a97fffffffff,818abffffffffff,808bfffffffffff
31460,85a90863fffffff,84a9087ffffffff,83a908fffffffff,82a90ffffffffff,81a93ffffffffff,80a9fffffffffff

In [12]:
coords = df["res5"].apply(h3.cell_to_latlng)

df["lat"] = coords.str[0]
df["lng"] = coords.str[1]

df

,res5,res4,res3,res2,res1,res0,lat,lng
0,858a44dbfffffff,848a44dffffffff,838a44fffffffff,828a47fffffffff,818a7ffffffffff,808bfffffffffff,-4.812937,-68.771130
1,85a8250bfffffff,84a8251ffffffff,83a825fffffffff,82a827fffffffff,81a83ffffffffff,80a9fffffffffff,-26.884631,-51.810270
2,858111b3fffffff,848111bffffffff,838111fffffffff,828117fffffffff,81813ffffffffff,8081fffffffffff,-11.858865,-40.536421
3,85a82193fffffff,84a8219ffffffff,83a821fffffffff,82a827fffffffff,81a83ffffffffff,80a9fffffffffff,-26.431929,-52.087525
4,858f6bc7fffffff,848f6bdffffffff,838f6bfffffffff,828f6ffffffffff,818f7ffffffffff,808ffffffffffff,-7.167453,-73.434036
...,...,...,...,...,...,...,...,...
31456,858a0693fffffff,848a069ffffffff,838a06fffffffff,828a07fffffffff,818a3ffffffffff,808bfffffffffff,-8.875093,-62.080033
31457,85a90bdbfffffff,84a90bdffffffff,83a90bfffffffff,82a90ffffffffff,81a93ffffffffff,80a9fffffffffff,-28.315915,-51.570951
31458,858a031bfffffff,848a031ffffffff,838a03fffffffff,828a07fffffffff,818a3ffffffffff,808bfffffffffff,-6.702183,-62.629658
31459,858a95a7fffffff,848a95bffffffff,838a95fffffffff,828a97fffffffff,818abffffffffff,808bfffffffffff,-4.178465,-54.709591
31460,85a90863fffffff,84a9087ffffffff,83a908fffffffff,82a90ffffffffff,81a93ffffffffff,80a9fffffffffff,-28.567725,-51.877520

In [13]:
for res in range(5, -1, -1):
    df[f'res{res}_idx'] = pd.factorize(df[f'res{res}'])[0]

df

,res5,res4,res3,res2,res1,res0,lat,lng,res5_idx,res4_idx,res3_idx,res2_idx,res1_idx,res0_idx
0,858a44dbfffffff,848a44dffffffff,838a44fffffffff,828a47fffffffff,818a7ffffffffff,808bfffffffffff,-4.812937,-68.771130,0,0,0,0,0,0
1,85a8250bfffffff,84a8251ffffffff,83a825fffffffff,82a827fffffffff,81a83ffffffffff,80a9fffffffffff,-26.884631,-51.810270,1,1,1,1,1,1
2,858111b3fffffff,848111bffffffff,838111fffffffff,828117fffffffff,81813ffffffffff,8081fffffffffff,-11.858865,-40.536421,2,2,2,2,2,2
3,85a82193fffffff,84a8219ffffffff,83a821fffffffff,82a827fffffffff,81a83ffffffffff,80a9fffffffffff,-26.431929,-52.087525,3,3,3,1,1,1
4,858f6bc7fffffff,848f6bdffffffff,838f6bfffffffff,828f6ffffffffff,818f7ffffffffff,808ffffffffffff,-7.167453,-73.434036,4,4,4,3,3,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31456,858a0693fffffff,848a069ffffffff,838a06fffffffff,828a07fffffffff,818a3ffffffffff,808bfffffffffff,-8.875093,-62.080033,31456,4458,69,45,9,0
31457,85a90bdbfffffff,84a90bdffffffff,83a90bfffffffff,82a90ffffffffff,81a93ffffffffff,80a9fffffffffff,-28.315915,-51.570951,31457,3949,71,46,10,1
31458,858a031bfffffff,848a031ffffffff,838a03fffffffff,828a07fffffffff,818a3ffffffffff,808bfffffffffff,-6.702183,-62.629658,31458,3944,222,45,9,0
31459,858a95a7fffffff,848a95bffffffff,838a95fffffffff,828a97fffffffff,818abffffffffff,808bfffffffffff,-4.178465,-54.709591,31459,4108,591,48,12,0
31460,85a90863fffffff,84a9087ffffffff,83a908fffffffff,82a90ffffffffff,81a93ffffffffff,80a9fffffffffff,-28.567725,-51.877520,31460,4109,73,46,10,1

In [16]:
for res in range(5, -1, -1):
    df[f'res{res}_cor'] = (df[f'res{res}_idx'] % 15) + 1

df

,res5,res4,res3,res2,res1,res0,lat,lng,res5_idx,res4_idx,res3_idx,res2_idx,res1_idx,res0_idx,res5_cor,res4_cor,res3_cor,res2_cor,res1_cor,res0_cor
0,858a44dbfffffff,848a44dffffffff,838a44fffffffff,828a47fffffffff,818a7ffffffffff,808bfffffffffff,-4.812937,-68.771130,0,0,0,0,0,0,1,1,1,1,1,1
1,85a8250bfffffff,84a8251ffffffff,83a825fffffffff,82a827fffffffff,81a83ffffffffff,80a9fffffffffff,-26.884631,-51.810270,1,1,1,1,1,1,2,2,2,2,2,2
2,858111b3fffffff,848111bffffffff,838111fffffffff,828117fffffffff,81813ffffffffff,8081fffffffffff,-11.858865,-40.536421,2,2,2,2,2,2,3,3,3,3,3,3
3,85a82193fffffff,84a8219ffffffff,83a821fffffffff,82a827fffffffff,81a83ffffffffff,80a9fffffffffff,-26.431929,-52.087525,3,3,3,1,1,1,4,4,4,2,2,2
4,858f6bc7fffffff,848f6bdffffffff,838f6bfffffffff,828f6ffffffffff,818f7ffffffffff,808ffffffffffff,-7.167453,-73.434036,4,4,4,3,3,3,5,5,5,4,4,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31456,858a0693fffffff,848a069ffffffff,838a06fffffffff,828a07fffffffff,818a3ffffffffff,808bfffffffffff,-8.875093,-62.080033,31456,4458,69,45,9,0,2,4,10,1,10,1
31457,85a90bdbfffffff,84a90bdffffffff,83a90bfffffffff,82a90ffffffffff,81a93ffffffffff,80a9fffffffffff,-28.315915,-51.570951,31457,3949,71,46,10,1,3,5,12,2,11,2
31458,858a031bfffffff,848a031ffffffff,838a03fffffffff,828a07fffffffff,818a3ffffffffff,808bfffffffffff,-6.702183,-62.629658,31458,3944,222,45,9,0,4,15,13,1,10,1
31459,858a95a7fffffff,848a95bffffffff,838a95fffffffff,828a97fffffffff,818abffffffffff,808bfffffffffff,-4.178465,-54.709591,31459,4108,591,48,12,0,5,14,7,4,13,1
31460,85a90863fffffff,84a9087ffffffff,83a908fffffffff,82a90ffffffffff,81a93ffffffffff,80a9fffffffffff,-28.567725,-51.877520,31460,4109,73,46,10,1,6,15,14,2,11,2

In [17]:
cont = 0

for res in range(5, -1, -1):
    df_aux = df[['lat','lng']]
    df_aux['resolucao'] = res
    df_aux['cor'] = df[f"res{res}_cor"]

    if cont == 0:
        df2 = df_aux.copy()
    else:
        df2 = pd.concat([df2, df_aux])

    cont = cont + 1

df2

             lat        lng  resolucao  cor
0      -4.812937 -68.771130          5    1
1     -26.884631 -51.810270          5    2
2     -11.858865 -40.536421          5    3
3     -26.431929 -52.087525          5    4
4      -7.167453 -73.434036          5    5
...          ...        ...        ...  ...
31456  -8.875093 -62.080033          0    1
31457 -28.315915 -51.570951          0    2
31458  -6.702183 -62.629658          0    1
31459  -4.178465 -54.709591          0    1
31460 -28.567725 -51.877520          0    2

[188766 rows x 4 columns]

In [18]:
df2.to_csv('carga.csv',index=False)

In [19]:
lat = -23.5505
lng = -46.6333

row = {
    f"res{res}": h3.latlng_to_cell(lat, lng, res)
    for res in range(9)
}

df3 = pd.DataFrame([row])
df3

,res0,res1,res2,res3,res4,res5,res6,res7,res8
0,80a9fffffffffff,81a83ffffffffff,82a817fffffffff,83a810fffffffff,84a8101ffffffff,85a8100ffffffff,86a8100c7ffffff,87a8100c0ffffff,88a8100c03fffff